name:                wonder-life
version:             0.1.0.0
github:              "githubuser/wonder-life"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/wonder-life#readme>

dependencies:
- base >= 4.7 && < 5
- extra
- time
- text
- uuid
- bytestring
- aeson
- rio
- vector
- mtl
- microlens
- microlens-mtl
- monad-logger
- transformers
- scientific
- katip
- warp
- servant

default-extensions:
- TemplateHaskell
- NoImplicitPrelude
- OverloadedStrings
- NamedFieldPuns
- RecordWildCards
- QuasiQuotes

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  wonder-life-api:
    main:                Main.hs
    source-dirs:         app/api
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wonder-life
    - servant-server
    - persistent
    - persistent-template
    - persistent-mysql
    - esqueleto
  wonder-life-gtk:
    main:                Main.hs
    source-dirs:         app/gtk
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wonder-life
    - http-client
    - servant-client
    - gi-gtk
    - haskell-gi-base
  wonder-life-terminal:
    main:                Main.hs
    source-dirs:         app/terminal
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wonder-life
    - brick
    - vty

tests:
  wonder-life-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wonder-life
